package com.gbsnowday.snowday;

import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.KeyStroke;

/**
 *
 * @author Corey
 */
public class About extends javax.swing.JDialog {
    
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 0;

    /**
     * Creates new form About
     * @param parent
     * @param modal
     */
    public About(javax.swing.JFrame parent, boolean modal) {
        initComponents();
        setTitle("About");
        setLocationRelativeTo(parent);
        
        //Setup hyperlinks
        web.setText("<html><a href=\\\"\\\">gbsnowday.weebly.com</a></html>");
        web.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
        mail.setText("<html><a href=\\\"\\\">gbsnowday@gmail.com</a></html>");
        mail.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
        twitter.setText("<html><a href=\\\"\\\">twitter.com/gbsnowday</a></html>");
        twitter.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
        //Start listeners
        web(web);
        mail(mail);
        twitter(twitter);
        
        // Close the dialog when Esc is pressed
        String okName = "OK";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), okName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(okName, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                doClose(RET_OK);
            }
        });
    }
    
    private void web(JLabel web) {
        web.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                try {
                    Desktop.getDesktop().browse(new URI("http://gbsnowday.weebly.com"));
                } catch (URISyntaxException | IOException ex) {                  
                }
            }
        });
    }
    
    private void twitter(JLabel twitter) {
        twitter.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                try {
                    Desktop.getDesktop().browse(new URI("http://twitter.com/gbsnowday"));
                } catch (URISyntaxException | IOException ex) {            
                }
            }
        });
    }

    private void mail(JLabel mail) {
        mail.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                try {
                    Desktop.getDesktop().mail(new URI("mailto:gbsnowday@gmail.com"));
                } catch (URISyntaxException | IOException ex) {                       
                }
            }
        });
    }

    /**
     * @return the return status of this dialog - one of RET_OK
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        picSnowday = new javax.swing.JLabel();
        lblGB = new javax.swing.JLabel();
        lblSnowday = new javax.swing.JLabel();
        lblDev = new javax.swing.JLabel();
        web = new javax.swing.JLabel();
        mail = new javax.swing.JLabel();
        twitter = new javax.swing.JLabel();
        lblVersion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About");
        setLocationByPlatform(true);
        setName("About"); // NOI18N
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        picSnowday.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gbsnowday/snowday/icon.png"))); // NOI18N

        lblGB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblGB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGB.setText("Grand Blanc Community Schools");

        lblSnowday.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblSnowday.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSnowday.setText("Snow Day Calculator");

        lblDev.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDev.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDev.setText("Developed by Corey Rowe");

        web.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        web.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        web.setText("gbsnowday.weebly.com");

        mail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mail.setText("gbsnowday@gmail.com");

        twitter.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        twitter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        twitter.setText("twitter.com/GBSnowDay");

        lblVersion.setText("v1.1.1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(picSnowday, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(web, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblGB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                            .addComponent(lblSnowday, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(twitter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDev, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblVersion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblGB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSnowday)
                        .addGap(18, 18, 18)
                        .addComponent(lblDev)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(web)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(twitter))
                    .addComponent(picSnowday))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(lblVersion))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getRootPane().setDefaultButton(okButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        doClose(RET_OK);
    }//GEN-LAST:event_okButtonActionPerformed

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_OK);
    }//GEN-LAST:event_closeDialog
    
    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                About dialog = new About(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDev;
    private javax.swing.JLabel lblGB;
    private javax.swing.JLabel lblSnowday;
    private javax.swing.JLabel lblVersion;
    private javax.swing.JLabel mail;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel picSnowday;
    private javax.swing.JLabel twitter;
    private javax.swing.JLabel web;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_OK;
}
